SET BASEDIR=%~dp0

SET MIGRATION_PROJECT=%BASEDIR%\\PostgreSqlMigration\\PostgreSqlMigration.csproj
SET MAIN_PROJECT=%BASEDIR%\\..\\src\\gestistate\\gestistate.csproj

SET SMUSDI_APPSETTINGS_FOLDER=%BASEDIR%\\..\\appsettings
SET SMUSDI_SERVICE_NAME=gestistate
SET ASPNETCORE_ENVIRONMENT=Development
SET POSTGRES_HOST=localhost
SET POSTGRES_DB=smusdi
SET POSTGRES_USER=smusdi
SET POSTGRES_PASSWORD=smusdi
SET POSTGRES_PORT=5432
SET MIGRATE_DATABASE=false
